// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epkrbpwsluhoraxglfgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwa3JicHdzbHVob3JheGdsZmdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NDQxNzQsImV4cCI6MjA3MTQyMDE3NH0.EY-x7l57p0Jr-FzJCdzHhkYuMR_ngJQwhkxn7WVdDCU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});